server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tms_db?createDatabaseIfNotExist=true
    username: root
    password: Password123!@#
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    "hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect"

  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mtawil25@gmail.com  # Replace with your email
    password: ioyc ghoo yckj ebqr   # Replace with your password
    sender:
      name: E-Commerce
      email: mtawil25@gmail.com  # Replace with your email
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


security:
  jwt:
    secret-key: e3v7R0dInm7k2wtV3ZG3WT7boHmcZc4l8tB+odtfv34=
    expiration-time: 86400000  # 1 day in milliseconds